// utils/suspiciousAgents.js

// Export a list of keywords commonly found in bad bots, scrapers, scanners, and known crawlers.
export const suspiciousAgents = [
  "Googlebot", "Telegram", "Bing", "bot", "above", "google", "softlayer", "amazonaws", "cyveillance",
  "compatible", "facebook", "netpilot", "calyxinstitute", "tor-exit", "apache-httpclient", "lssrocketcrawler",
  "Trident", "X11", "crawler", "urlredirectresolver", "jetbrains", "spam", "windows95", "windows98",
  "acunetix", "netsparker", "007ac9", "008", "192.comagent", "200pleasebot", "360spider", "4seohuntbot",
  "50.nu", "a6-indexer", "admantx", "amznkassocbot", "aboundexbot", "aboutusbot", "abravespider", "accelobot",
  "acoonbot", "addthis.com", "adsbot-google", "ahrefsbot", "alexabot", "amagit.com", "analytics", "antbot",
  "apercite", "aportworm", "arabot", "crawl", "slurp", "spider", "seek", "accoona", "adressendeutschland",
  "ah-ha.com", "ahoy", "altavista", "ananzi", "anthill", "appie", "arachnophilia", "arale", "araneo", "aranha",
  "architext", "aretha", "arks", "asterias", "atlocal", "atn", "atomz", "augurfind", "backrub", "bannana_bot",
  "baypup", "bdfetch", "bigbrother", "biglotron", "bjaaland", "blackwidow", "blaiz", "blog", "blo.", "bloodhound",
  "boitho", "booch", "bradley", "butterfly", "calif", "cassandra", "ccubee", "cfetch", "charlotte", "churl",
  "cienciaficcion", "cmc", "collective", "comagent", "combine", "computingsite", "csci", "curl", "cusco",
  "daumoa", "deepindex", "delorie", "depspid", "deweb", "dieblindekuh", "digger", "ditto", "dmoz", "docomo",
  "downloadexpress", "dtaagent", "dwcp", "ebiness", "ebingbong", "e-collector", "ejupiter", "emacs-w3searchengine",
  "esther", "evliyacelebi", "ezresult", "falcon", "felixide", "ferret", "fetchrover", "fido", "findlinks", "fireball",
  "fishsearch", "fouineur", "funnelweb", "gazz", "gcreep", "genieknows", "getterroboplus", "geturl", "glx", "goforit",
  "golem", "grabber", "grapnel", "gralon", "griffon", "gromit", "grub", "gulliver", "hamahakki", "harvest", "havindex",
  "helix", "heritrix", "hkuwwwoctopus", "homerweb", "htdig", "htmlindex", "html_analyzer", "htmlgobble", "hubater",
  "hyper-decontextualizer", "ia_archiver", "ibm_planetwide", "ichiro", "iconsurf", "iltrovatore", "image.kapsi.net",
  "imagelock", "incywincy", "indexer", "infobee", "informant", "ingrid", "inktomisearch.com", "inspectorweb",
  "intelliagent", "internetshinchakubin", "ip3000", "iron33", "israeli-search", "ivia", "jack", "jakarta", "javabee",
  "jetbot", "jumpstation", "katipo", "kdd-explorer", "kilroy", "knowledge", "kototoi", "kretrieve", "labelgrabber",
  "lachesis", "larbin", "legs", "libwww", "linkalarm", "linkvalidator", "linkscan", "lockon", "lwp", "lycos", "magpie",
  "mantraagent", "mapoftheinternet", "marvin/", "mattie", "mediafox", "mediapartners", "mercator", "merzscope",
  "microsofturlcontrol", "minirank", "miva", "mj12", "mnogosearch", "moget", "monster", "moose", "motor", "multitext",
  "muncher", "muscatferret", "mwd.search", "myweb", "najdi", "nameprotect", "nationaldirectory", "nazilla", "ncsabeta",
  "nec-meshexplorer", "nederland.zoek", "netcartawebmapengine", "netmechanic", "netresearchserver", "netscoop",
  "newscan-online", "nhse", "nokia6682/", "nomad", "noyona", "nutch", "nzexplorer", "objectssearch", "occam", "omni",
  "opentext", "openfind", "openintelligencedata", "orbsearch", "osis-project", "packrat", "pageboy", "pagebull",
  "page_verifier", "panscient", "parasite", "partnersite", "patric", "pear.", "pegasus", "peregrinator", "pgpkeyagent",
  "phantom", "phpdig", "picosearch", "piltdownman", "pimptrain", "pinpoint", "pioneer", "piranha", "plumtreewebaccessor",
  "pogodak", "poirot", "pompos", "poppelsdorf", "poppi", "populariconoclast", "psycheclone", "publisher", "python",
  "rambler", "ravensearch", "roach", "roadrunner", "roadhouse", "robbie", "robofox", "robozilla", "rules", "salty",
  "sbider", "scooter", "scoutjet", "scrubby", "search.", "searchprocess", "semanticdiscovery", "senrigan", "sg-scout",
  "shai'hulud", "shark", "shopwiki", "sidewinder", "sift", "silk", "simmany", "sitesearcher", "sitevalet", "sitetech-rover",
  "skymob.com", "sleek", "smartwit", "sna-", "snappy", "snooper", "sohu", "speedfind", "sphere", "sphider", "spinner",
  "spyder", "steeler/", "suke", "suntek", "supersnooper", "surfnomore", "sven", "sygol", "szukacz", "telegrambot",
  "twitterbot", "meta", "scrapy", "screamingfrog", "duckduckbot", "baiduspider", "mj12bot", "semrushbot", "ahrefsbot",
  "yandexbot", "facebookexternalhit", "whatsapp", "drweb", "scanurl", "phishtank", "trendmicro", "sucuri.net",
  "p3pwgdsn", "cloudflare", "masscan", "masscan-ng", "nmap", "fuzz", "wappalyzer", "sitelock", "uptimerobot"
];
